# Generated by Django 4.2.16 on 2025-01-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_brand_rename_tbl_admin_tbl_adminreg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_photo', models.CharField(max_length=100)),
                ('Product_price', models.CharField(max_length=100)),
            ],
        ),
    ]
