# Generated by Django 4.2.16 on 2025-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_delete_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_photo', models.FileField(upload_to='assets/product/photo')),
                ('product_price', models.CharField(max_length=100)),
            ],
        ),
    ]
