# Generated by Django 4.2.20 on 2025-03-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_product_tbl_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_product',
            old_name='catgeory',
            new_name='category',
        ),
    ]
