# Generated by Django 5.2 on 2025-04-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_size_tbl_product_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='size',
        ),
        migrations.CreateModel(
            name='tbl_productsize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_size')),
            ],
        ),
    ]
