# Generated by Django 4.2.16 on 2025-01-16 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_brand_rename_tbl_admin_tbl_adminreg_and_more'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_reg',
            old_name='reg_district',
            new_name='reg_contact',
        ),
        migrations.RemoveField(
            model_name='tbl_reg',
            name='reg_place',
        ),
        migrations.AddField(
            model_name='tbl_reg',
            name='place',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_reg',
            name='user_photo',
            field=models.FileField(default=2, upload_to='Assets/users/photo/'),
            preserve_default=False,
        ),
    ]
