# Generated by Django 5.2 on 2025-04-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_remove_tbl_product_size_tbl_productsize'),
        ('User', '0002_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_size'),
        ),
    ]
