# Generated by Django 5.2 on 2025-04-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='reply',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
