# Generated by Django 5.2 on 2025-04-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_remove_tbl_product_size_tbl_productsize'),
        ('Guest', '0003_rename_tbl_reg_tbl_user'),
        ('User', '0005_tbl_complaint_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
